"use server";

import { db } from "@/lib/db";
import { hashPassword } from "@/lib/auth";
import { getSession } from "@/lib/session";
import { redirect } from "next/navigation";

export async function setupOrganization(formData: FormData) {
  const orgName = (formData.get("org_name") as string)?.trim();
  const fullName = (formData.get("full_name") as string)?.trim();
  const email = (formData.get("email") as string)?.trim().toLowerCase();
  const password = formData.get("password") as string;

  if (!orgName || !fullName || !email || !password) {
    return { error: "All fields are required." };
  }

  if (password.length < 6) {
    return { error: "Password must be at least 6 characters." };
  }

  // Check if email is already used
  const { data: existing } = await db
    .from("organization_admins")
    .select("id")
    .eq("email", email)
    .single();
  if (existing) return { error: "Email already in use." };

  // Create organization (slug auto-generated by DB trigger)
  const { data: org, error: orgError } = await db
    .from("organizations")
    .insert({ name: orgName, slug: orgName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "org" })
    .select("id, slug")
    .single();

  if (orgError || !org) {
    return { error: orgError?.message ?? "Failed to create organization." };
  }

  const passwordHash = await hashPassword(password);

  const { data: admin, error: adminError } = await db
    .from("organization_admins")
    .insert({
      organization_id: org.id,
      email,
      password_hash: passwordHash,
      full_name: fullName,
    })
    .select("id, email, full_name, organization_id")
    .single();

  if (adminError || !admin) {
    return { error: adminError?.message ?? "Failed to create admin account." };
  }

  const session = await getSession();
  session.id = admin.id;
  session.email = admin.email;
  session.fullName = admin.full_name;
  session.role = "org_admin";
  session.organizationId = admin.organization_id;
  session.orgSlug = org.slug;
  await session.save();

  redirect(`/org/${org.slug}/admin`);
}
